%YAML:1.0

Version: 1.0

#--------------------------------------------------------------------------------------------
# General Parameters
#--------------------------------------------------------------------------------------------

# rate of systemmatic samplling for events:3
sampling_rate: 3
# rate of systemmatic samplling for globally aligned events:1
map_sampling_rate: 1
# sliding window size for globally aligned events
sliding_window_size: 1000
# event image theshold T_rho
event_image_threshold: 5
# on/off (1/0) the proposed method 
rotation_estimation: 1
# 0: runs in real-time, x: runs for the x temporal windows instead of real-time operation.
# run_index需大於optimization_view_index才會顯示批次處理結果圖
run_index: 0


# view contrast maximization process after view_idex
optimization_view_index: 1e3
# view angle difference range to utilize globally aligned events (unit: radians) 0.628rad=36deg 0.436rad=25deg 
# Threshold on view angle difference for selecting globally aligned events, also used to limit event accumulation during global alignment. (unit: radians)
mapping_interval: 0.436
# scale of view for globally aligned events
map_scale: 2

#--------------------------------------------------------------------------------------------
# Event Parameters
#--------------------------------------------------------------------------------------------
#delta_time: 0.025, max_event_num: 1e5
delta_time: 0.025
max_event_num: 1e5

#--------------------------------------------------------------------------------------------
# Optimizer Parameters
#--------------------------------------------------------------------------------------------

# maximum iteration
Optimizer.max_iter: 65
# step size | optimization rate: 0.05
Optimizer.eta_angular_velocity: 0.05
# smoothing factor | the degree of weigthing decrease in geometric moving average: 0.995
Optimizer.rho_angular_velocity: 0.995

# step size | optimization rate: 0.0025
Optimizer.eta_angular_position: 0.0025
# smoothing factor | the degree of weigthing decrease in geometric moving average: 0.05
Optimizer.rho_angular_position: 0.05

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
# size of real targets

# original image size for camera
width: 240
height: 180

# focus
Camera.fx: 199.092366542
Camera.fy: 198.82882047
# center
Camera.cx: 132.192071378
Camera.cy: 110.712660011
# radial distortion
Camera.rd1: -0.368436311798
Camera.rd2: 0.150947243557

visualize.denom: 3
